Create strukturierenDB.md
DevCraft-Academy/exercises pull request #107
Opened 2024-12-30 15:22 UTC by BastiEbel

2025-05-27 18:22 UTC, vsaeu commented on BastiEbel/strukturierenDB.md
> +One-To-Many zu Kommentar (ein Beitrag kann viele Kommentare haben)
Braucht es nicht, weil die FK im Kommentar zum Beitrag vorhanden ist

2025-05-27 18:26 UTC, vsaeu requested changes
Keine Bidirectionalen foreign keys

2025-05-27 18:26 UTC, vsaeu commented on BastiEbel/strukturierenDB.md
> +Many-To-One zu Nutzer (ein Kommentar wird von einem Nutzer verfasst)
Wenn zwei Entitäten miteinander verbunden sind, gehört der foreign key nur in eine entität, nicht in beide.
der FK gehört in die Entität die "many" ist. also hier zB in Kommentar die NutzerID.
Das kam in der Lektion nicht so gut raus. Habe ich selbst bei meiner Übung falsch und erst am zweiten tag durch weitere Recherche herausgefunden^^

2026-06-30 17:53 UTC, clemenshelm approved these changes
Hallo! ✅

Fokussierte Lösung für die Übung — danke, ein PR pro Übung ist genau richtig. Kern der Aufgabe erkannt und umgesetzt.

Approv! 🎉 Weiter so!

2026-06-30 17:53 UTC, merged