Create Konfigurator_fuer_individuelle_PC_Systeme.js
DevCraft-Academy/exercises pull request #13
Opened 2024-06-24 20:52 UTC by pkrainer

2024-06-25 10:10 UTC, hola-soy-milk commented
Would love to invite @derfabio to please review this!

2025-05-06 16:30 UTC, RubinaWeinzettl approved these changes
Aus meiner Sicht sieht das gut aus mit dem Virtual Proxy! Ich habe das File allerdings noch nicht testen können - Ergebnis vom Test unten.

2025-05-07 16:40 UTC, RubinaWeinzettl requested changes
Ich habe das File auf node getestet und es hat einen Syntax error geworfen. Ich habe den Fehler gefunden und im Code markiert

2025-05-07 16:40 UTC, RubinaWeinzettl commented on pkrainer/Neuer Ordner (2)/Konfigurator_fuer_individuelle_PC_Systeme.js
> +  }
in Zeile 42 ist eine zweite Klammer zu

2026-06-30 18:18 UTC, clemenshelm approved these changes
Hallo! ✅

Fokussierte Lösung für die Übung — danke, ein PR pro Übung ist genau richtig. Kern der Aufgabe erkannt und umgesetzt.

Approv! 🎉 Weiter so!

2026-06-30 18:18 UTC, merged