commit
DevCraft-Academy/exercises pull request #17
Opened 2024-06-27 21:33 UTC by pkrainer

2025-05-13 13:13 UTC, RubinaWeinzettl requested changes
Da die Ausführung von dem Code nicht geklappt hat, würde ich dir vorschlagen, den Code nocheinmal zu überarbeiten und zu testen. Vorschläge von mir findest du bei den entsprechenden Files.

Ein Tipp der mir beim Debuggen hilft, wenn ich nicht weiß was das heißt, was in der Console steht:
ChatGPD oder eine andere KI zum Debuggen verwenden
Du kannst in die Prompt deine Filestruktur und deinen Code reinschreiben und den Fehler, den die Console wirft. Dann sagt ChatGPD dir, was falsch ist. Funktioniert bei mir eigentlich meistens gut!
Das Beste daran ist, dass Chat GPD dir auch erklärt, was und warum das Ganze nicht funktioniert hat.
Du kannst ChatGPD auch bitten, den Code gleich umzuschreiben, so dass er funktioniert.
Oder du kannst weitere Fragen stellen, wenn du manche Themen noch nicht ganz verstanden hast. Ich habe dadurch viel gelernt (auch wenn bekannt ist, dass die Infos von KIs auch manchmal mit Vorsicht zu genießen sind, aber bei Basis Sachen klappt es ganz gut)

2025-05-13 13:13 UTC, RubinaWeinzettl commented on pkrainer/Verhaltensmuster/verhaltensmuster.html
> +<form id="validationForm">
1. Kleiner Tipp: Das File für die Anzeige, wird so weit ich weiß standardmäßig mit index.html benannt
Solche Standards helfen Entwickler:innen schneller zu erkennen, wo sich das Frontend befindet.

2. Semantische HTML Tags schaden meiner Ansicht nach auch bei einer Übung nicht, weil du so sicher stellen kannst, das alles richtig dargestellt wird.
Vorschlag von meiner Seite: hier am Anfang des Dokuments
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Flexibles Formular-Validierungssystems mit Behavioral Design Patterns</title>
</head>
```

2025-05-13 13:13 UTC, RubinaWeinzettl commented on pkrainer/Verhaltensmuster/verhaltensmuster.html
> +  </form>
Beim Testen des Formulars fällt mir auf, dass der JS Code gar nicht ausgeführt wird. Das liegt daran, dass der Script-Tag mit Angabe des js Files fehlt.
Hier wieder mein Vorschlag für das Ende des Files ab dem </form> (mit Script Tag, wo dein JS verlinkt ist und allen Tags geschlossen):
```
<script type="module" src="./verhaltensmuster.js"></script>
</body>
</html>
```

2025-05-13 13:13 UTC, RubinaWeinzettl commented on pkrainer/Verhaltensmuster/verhaltensmuster.js
> +
Beim Testen bekomme ich in der Console folgenden Fehler:
"Uncaught ReferenceError: Cannot access 'Validation' before initialization
    at verhaltensmuster.html?email=qwq&phone=&password=:26:39"
    
  Das ist deswegen, weil du deine Basis-Klasse Validation erst nach PhoneValidation und EmailValidation definierst. Die Klasse Validation muss zuerst definiert werden.

Ich habe deinen Code mit Chat GPD debuggt und das war das Ergebnis (das beim Testen bei mir auch funktioniert hat):
```
// Basisklasse zuerst definieren
class Validation {
  validate(value) {
    throw new Error("Validation not possible");
  }
}

// Konkrete Validierungsstrategien

class EmailValidation extends Validation {
  validate(value) {
    const re = /^\S+@\S+\.\S+$/;
    return re.test(value) ? "" : "E-Mail-Adresse ungültig";
  }
}

class PasswordValidation extends Validation {
  validate(value) {
    if (!/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,}$/.test(value)) {
      return "Passwort muss mindestens 8 Zeichen, Groß- und Kleinbuchstaben sowie eine Zahl enthalten.";
    }
    return "";
  }
}

class PhoneValidation extends Validation {
  validate(value) {
    const re = /^\+\d{6,15}$/; // z. B. +436601234567
    return re.test(value) ? "" : "Ungültige Telefonnummer. Erwartet: +1234567890.";
  }
}

// Kontextklasse für Strategy Pattern
class Validator {
  constructor(strategy) {
    this.strategy = strategy;
  }

  validate(value) {
    return this.strategy.validate(value);
  }
}

// Formularverarbeitung
document.getElementById("validationForm").addEventListener("submit", (e) => {
  e.preventDefault();

  const emailValidator = new Validator(new EmailValidation());
  const passwordValidator = new Validator(new PasswordValidation());
  const phoneValidator = new Validator(new PhoneValidation());

  const emailValue = document.getElementById("email").value;
  const phoneValue = document.getElementById("phone").value;
  const passwordValue = document.getElementById("password").value;

  const emailError = emailValidator.validate(emailValue);
  const phoneError = phoneValidator.validate(phoneValue);
  const passwordError = passwordValidator.validate(passwordValue);

  document.getElementById("email-error").textContent = emailError;
  document.getElementById("phone-error").textContent = phoneError;
  document.getElementById("password-error").textContent = passwordError;

  if (!emailError && !phoneError && !passwordError) {
    console.log("Formular erfolgreich validiert!");
    // Optional: Formular absenden oder weiterverarbeiten
  }
});
```

2026-06-30 18:18 UTC, clemenshelm approved these changes
Hallo! ✅

Fokussierte Lösung für die Übung — danke, ein PR pro Übung ist genau richtig. Kern der Aufgabe erkannt und umgesetzt.

Approv! 🎉 Weiter so!

2026-06-30 18:18 UTC, merged